In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\yashvi khatri\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\yashvi khatri\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yashvi khatri\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yashvi khatri\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yashvi khatri\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\yashvi khatri\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

WARNING: Ignoring invalid distribution ~ip (C:\Users\YASHVI KHATRI\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\YASHVI KHATRI\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\YASHVI KHATRI\AppData\Local\Programs\Python\Python312\Lib\site-packages)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

df = pd.read_csv('dataset/synthetic_logs.csv')
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [2]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [3]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [4]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN
import numpy as np

# Load pre-trained SentenceTransformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embedding for log messages
embeddings = model.encode(df['log_message'].tolist())
embeddings[:2]

c:\Users\YASHVI KHATRI\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

array([[-1.02939621e-01,  3.35459299e-02, -2.20260788e-02,
         1.55102671e-03, -9.86922998e-03, -1.78956211e-01,
        -6.34409636e-02, -6.01761751e-02,  2.81109344e-02,
         5.99620566e-02, -1.72618441e-02,  1.43365189e-03,
        -1.49560034e-01,  3.15289968e-03, -5.66030852e-02,
         2.71685794e-02, -1.49890725e-02, -3.54037471e-02,
        -3.62936258e-02, -1.45410104e-02, -5.61492424e-03,
         8.75538811e-02,  4.55120690e-02,  2.50963569e-02,
         1.00187585e-02,  1.24267116e-02, -1.39923558e-01,
         7.68696368e-02,  3.14095393e-02, -4.15245304e-03,
         4.36902978e-02,  1.71250217e-02, -8.00951123e-02,
         5.74005917e-02,  1.89092029e-02,  8.55261832e-02,
         3.96398790e-02, -1.34371832e-01, -1.44369598e-03,
         3.06706410e-03,  1.76854059e-01,  4.44887346e-03,
        -1.69275049e-02,  2.24266183e-02, -4.35049459e-02,
         6.09031459e-03, -9.98169929e-03, -6.23973384e-02,
         1.07372347e-02, -6.04892615e-03, -7.14660883e-02,
        -8.45806208e-03, -3.18020098e-02, -1.00518361e-01,
         2.25821073e-04, -1.89341456e-02, -3.17793638e-02,
         4.00861204e-02,  2.19178293e-02, -2.59528998e-02,
         5.84525205e-02, -8.12510103e-02,  2.12029032e-02,
        -5.02687618e-02,  1.32057443e-02,  1.32675562e-03,
         2.27062963e-02, -3.45793739e-02,  3.91546711e-02,
        -2.09433362e-02,  3.24824220e-03,  4.43960801e-02,
        -9.85357612e-02, -2.88894940e-02, -6.85023051e-03,
         5.38818985e-02,  6.46110624e-02, -2.45060883e-02,
         9.21828672e-02, -7.49868676e-02,  1.23995133e-02,
        -1.00026526e-01, -4.64910865e-02,  6.01569973e-02,
        -2.46480685e-02, -7.08075762e-02, -2.77270991e-02,
         9.72610861e-02,  3.85841280e-02, -1.44292591e-02,
        -7.46897538e-04, -1.04305148e-02, -1.61843114e-02,
         4.43627834e-02,  9.25997272e-03,  7.14165568e-02,
         6.37917444e-02,  4.94931042e-02, -6.02567531e-02,
         4.04805318e-02, -3.42860520e-02, -1.93880983e-02,
         6.61233813e-02,  6.01589233e-02,  1.09371580e-02,
        -5.38629526e-03,  1.44580211e-02,  9.25429612e-02,
        -3.14564072e-02, -1.84351616e-02,  9.91876144e-03,
        -1.85574312e-02,  1.31279859e-03,  2.26629745e-05,
         2.02737795e-03,  2.75257118e-02, -4.81927581e-02,
         5.42825721e-02, -7.32067078e-02,  4.88667525e-02,
         4.98489887e-02, -9.01146699e-03, -4.68905792e-02,
        -4.25886661e-02, -8.19523782e-02,  3.87106203e-02,
         7.85503760e-02,  1.46077067e-32,  1.66706145e-02,
         5.25494181e-02, -1.82448998e-02, -1.26686292e-02,
         6.52837604e-02, -2.11777370e-02, -4.06322777e-02,
         4.14947569e-02, -2.48361360e-02, -1.33068077e-02,
        -5.46754003e-02, -5.99124760e-04, -4.89244144e-03,
        -6.27359375e-02, -3.84878255e-02, -6.13543577e-02,
         8.27405676e-02,  2.34379657e-02, -8.63093045e-03,
         1.31002655e-02,  6.44215122e-02, -4.41361219e-02,
        -6.98633268e-02, -7.36060068e-02, -4.33264412e-02,
         6.96520926e-03, -5.05956709e-02, -1.60912108e-02,
        -5.66793717e-02,  3.35453334e-03,  5.34115024e-02,
         2.47761402e-02, -1.47985825e-02, -2.93242820e-02,
         7.30227828e-02, -1.86833814e-02,  8.13137069e-02,
        -2.69967411e-02, -5.68056516e-02, -6.59388527e-02,
        -5.95393451e-03,  2.85312887e-02, -7.85357729e-02,
        -2.76692025e-03, -3.26469308e-03, -9.28333178e-02,
        -7.27363080e-02, -3.31903547e-02,  1.01411119e-01,
         9.79882032e-02, -9.78740677e-02,  1.98667776e-02,
         2.38836855e-02, -1.81672368e-02, -3.73708606e-02,
         1.96551462e-03,  6.34425357e-02,  1.18271383e-02,
        -1.12041235e-02, -3.87317166e-02,  9.32424441e-02,
         4.26630303e-03, -1.66872274e-02, -6.87463731e-02,
         1.55120119e-02, -4.97755408e-02,  3.34493071e-02,
         8.00032616e-02,  2.12281998e-02,  1.34581864e-01,
        -2.30729971e-02,  5.53858951e-02,  3.07558309e-02,
        -2.93905679e-02,  2.31905282e-02, -9.34307650e-02,
         7.58034438e-02, -5.21205645e-03, -5.14523163e-02,
         3.32688987e-02,  3.67962681e-02, -1.06449733e-02,
         1.01634972e-02, -2.07650959e-02, -5.85519075e-02,
         4.79328409e-02,  2.13694554e-02,  8.76213461e-02,
         3.35497991e-03, -3.80336717e-02, -1.81205049e-02,
         6.87446119e-03,  5.15879802e-02, -4.75599207e-02,
        -6.12065569e-02, -1.45483574e-32,  4.12800582e-03,
         4.59642522e-03, -5.63900620e-02,  4.32464341e-03,
        -1.09438878e-03,  9.31957830e-03, -2.20269226e-02,
         5.79564013e-02, -1.44788129e-02,  4.64155897e-02,
         1.43542856e-01, -6.89756572e-02,  6.09631799e-02,
        -8.93743932e-02,  2.40919553e-02,  2.06010137e-02,
        -2.82415655e-02, -6.48315474e-02,  5.64795882e-02,
        -7.48343859e-03, -3.52058075e-02,  8.51060748e-02,
         1.30360126e-02,  2.02258099e-02, -1.44390957e-02,
        -4.63719293e-02,  1.77209694e-02,  1.59105789e-02,
        -9.51009542e-02, -3.54526713e-02,  2.08696295e-02,
         3.84391076e-03, -8.77918229e-02,  6.44575506e-02,
         1.44171268e-02,  3.84730729e-03,  4.70991693e-02,
         4.94661443e-02,  1.53862210e-02, -2.59578843e-02,
         9.10894498e-02,  1.83307454e-02, -5.89206740e-02,
         2.51992662e-02, -3.30373719e-02,  8.23344663e-02,
         1.74792334e-02,  6.48047328e-02, -1.19673805e-02,
        -3.31778601e-02,  3.00178099e-02,  3.54220234e-02,
        -1.39624393e-02,  6.69272617e-02,  3.87919657e-02,
         6.06916696e-02,  1.17959117e-03, -2.38786712e-02,
        -1.26930416e-01,  1.13846557e-02,  1.59290414e-02,
        -1.29426895e-02, -8.63248035e-02,  8.53658840e-03,
         6.03761002e-02,  1.51122017e-02, -1.19132400e-01,
         1.15235038e-02,  5.97089455e-02, -3.93346138e-02,
         1.55673055e-02,  1.04602147e-02, -4.72456738e-02,
        -2.59243008e-02,  9.98525135e-03,  3.07146199e-02,
        -7.14844316e-02,  6.98957872e-03, -1.55132934e-02,
         2.18863748e-02, -2.78145801e-02,  6.92733228e-02,
        -2.75903214e-02,  2.62429882e-02,  3.52561958e-02,
        -4.26419526e-02,  7.46287871e-04,  6.59866631e-02,
        -5.15106022e-02, -3.58434059e-02, -6.53442694e-03,
        -2.75858324e-02, -1.00125544e-01,  7.83325657e-02,
        -1.45799080e-02, -6.18457179e-08,  2.00325456e-02,
         6.59784898e-02, -2.04702690e-02,  1.64044425e-02,
         7.63000920e-02,  7.32182786e-02,  5.65787405e-03,
        -6.97764801e-04, -3.63795622e-03,  6.02394044e-02,
        -3.27187665e-02, -6.45838603e-02, -5.97952567e-02,
        -1.76695641e-02,  6.10138522e-03, -5.63487643e-03,
        -1.22972183e-01,  6.35819063e-02, -2.19431687e-02,
        -1.16406433e-01,  2.34366097e-02, -7.23525062e-02,
         2.31773779e-02, -6.55987337e-02, -7.42682219e-02,
         2.60146204e-02,  3.59758437e-02,  7.68432915e-02,
        -3.08057349e-02, -2.34794486e-02, -6.30426407e-02,
        -3.62158231e-02, -1.03559922e-02, -4.75602224e-02,
        -2.87522003e-02,  2.96400934e-02, -5.26889460e-03,
         5.67889474e-02, -3.74488183e-03,  3.09612919e-02,
         3.48227099e-02,  3.78607623e-02,  2.10155863e-02,
         2.70691421e-02,  5.25519922e-02,  7.16229305e-02,
        -5.53753413e-03,  4.01093587e-02,  5.16276620e-02,
        -2.67314054e-02,  5.94224073e-02, -4.29224111e-02,
        -1.19760884e-02,  3.05985343e-02, -7.40331262e-02,
         1.84221733e-02, -8.64863861e-03, -8.83557796e-02,
        -5.91984205e-02, -1.00870449e-04,  1.12913653e-01,
         4.57792962e-03, -4.25971560e-02,  3.22619220e-03],
       [ 8.04576185e-03, -3.57392468e-02,  4.93873730e-02,
        -7.19185825e-03,  6.17665821e-04, -9.05685350e-02,
         5.75594753e-02, -4.39446531e-02,  1.74751654e-02,
         5.21203354e-02, -4.62332144e-02,  2.49039568e-02,
         4.80811410e-02,  6.86636791e-02,  3.56146693e-02,
         3.00089307e-02,  2.61449553e-02, -9.05240998e-02,
        -8.02173838e-02,  5.04851192e-02, -7.90870637e-02,
        -1.76856108e-03, -2.48927083e-02,  9.02152732e-02,
         5.83697017e-03, -6.91071078e-02, -6.67965636e-02,
        -6.99113356e-03, -1.04566008e-01, -2.66473927e-02,
         3.05639915e-02,  2.02934500e-02,  2.25454606e-02,
        -4.22688248e-03,  1.11173093e-02,  6.78261071e-02,
         1.06073208e-02,  7.56636187e-02, -8.22777674e-02,
         8.45731236e-03, -6.97611943e-02, -4.21974584e-02,
        -1.05674630e-02,  2.23673414e-02,  5.64496480e-02,
         8.16504005e-03,  1.09344110e-01,  3.16564851e-02,
        -1.76923778e-02, -3.21071260e-02, -3.39975730e-02,
        -4.91787039e-04,  3.72877298e-03,  2.83771306e-02,
        -1.28521621e-02, -1.07931939e-03, -6.32418990e-02,
         6.89900517e-02,  1.77270509e-02, -5.20959869e-02,
         8.28310382e-03,  5.45032956e-02, -5.42099960e-02,
        -4.53332998e-02, -4.07494418e-02, -2.82698032e-02,
         1.23605859e-02, -2.13815887e-02, -2.36265659e-02,
         1.25318030e-02, -2.37170551e-02,  3.97411250e-02,
        -1.24362260e-01,  7.60625079e-02,  5.50833903e-02,
         8.28216821e-02,  2.97118723e-02, -1.84067544e-02,
        -1.96195133e-02,  5.54319136e-02, -3.49144675e-02,
        -4.14678045e-02, -3.37047428e-02,  7.31324255e-02,
         4.41836789e-02,  2.55247131e-02, -8.26404616e-03,
        -1.07322931e-02, -4.26243618e-02, -2.84961821e-03,
         7.38559291e-02,  2.27768160e-02,  7.15402188e-04,
         4.36012372e-02,  5.09079583e-02,  6.38482794e-02,
        -2.73155253e-02, -6.55021071e-02, -7.69265145e-02,
         3.55171151e-02,  9.60493982e-02,  2.18195897e-02,
         1.20155131e-02, -1.17863305e-02, -4.57925070e-03,
        -8.58033728e-03,  3.37150693e-02,  2.31918097e-02,
        -7.58325830e-02, -5.23879230e-02,  4.53934334e-02,
        -3.80785801e-02, -3.34904902e-02,  9.20353085e-02,
         2.87688933e-02, -3.33817117e-02, -1.95852108e-03,
        -3.04566202e-04, -1.70499310e-02,  2.85335928e-02,
        -8.81096274e-02, -4.02253084e-02, -4.00093086e-02,
        -1.03193047e-02, -2.51968410e-02,  2.14093532e-02,
         1.31045192e-01, -5.29633949e-34, -1.09651729e-01,
         1.29811550e-02,  5.92655642e-03,  4.73506264e-02,
        -8.60297494e-03, -3.67089324e-02,  3.05214860e-02,
         5.53066954e-02, -4.71985564e-02, -1.25118736e-02,
        -1.15366414e-01,  9.08002816e-03,  1.07346483e-01,
        -4.94734757e-02, -1.34290308e-02, -4.61562648e-02,
         2.45320350e-02,  9.45075881e-03,  2.04323679e-02,
        -3.99918556e-02, -4.67825681e-02,  2.21171770e-02,
        -4.58187349e-02, -8.13274179e-03, -7.65674561e-03,
         1.92284323e-02,  4.85845245e-02, -2.55903024e-02,
         1.61537575e-03, -1.37180295e-02,  9.67307854e-03,
         7.36415293e-03,  1.14088180e-02,  1.28853440e-01,
         7.71837868e-03,  7.06362426e-02,  2.54451931e-02,
         4.06523906e-02,  2.44039688e-02,  1.43776927e-02,
        -6.00932464e-02,  7.38180652e-02, -2.44700834e-02,
         8.98901224e-02,  3.17052123e-03,  1.01834461e-01,
         4.17742170e-02, -5.95177747e-02, -3.23181786e-02,
         3.80938612e-02,  1.21155744e-02, -4.07834351e-02,
         2.84823384e-02,  4.90988344e-02, -9.35708452e-03,
         6.50074184e-02,  7.23532215e-02, -1.67793650e-02,
        -8.22419859e-03, -1.61572956e-02,  5.96225746e-02,
        -3.36083621e-02,  2.12108660e-02, -6.06091060e-02,
         1.54377684e-01, -7.24145994e-02, -3.77272107e-02,
        -3.26890126e-02, -1.80384947e-03, -1.01960273e-02,
        -1.60679489e-03, -6.91846684e-02,  8.28444734e-02,
         9.88839641e-02,  3.45466682e-03, -9.90248248e-02,
        -3.52827050e-02, -7.13178664e-02, -4.96000536e-02,
        -3.43954377e-02, -8.13042298e-02,  4.81447838e-02,
         5.00682229e-03, -2.21499652e-02, -5.60057051e-02,
         1.00067258e-02, -3.59794311e-02,  1.06184311e-01,
        -4.54196706e-02,  7.16393366e-02, -2.36773379e-02,
         9.98142175e-03,  2.73602083e-02,  1.05985455e-01,
         4.60163578e-02,  9.59028719e-34, -1.12306975e-01,
         2.78912187e-02, -3.35900560e-02,  5.39242551e-02,
        -2.22291835e-02,  1.53769404e-02,  3.10411453e-02,
         3.39011215e-02,  7.43167028e-02,  3.42470743e-02,
        -3.35053541e-03, -2.05350555e-02, -3.62370089e-02,
         2.29334161e-02, -3.01992092e-02, -1.00819916e-01,
         3.29194255e-02,  6.77542984e-02,  1.35645261e-02,
        -5.20545896e-03, -6.58158362e-02,  9.54550877e-02,
        -1.34039111e-02,  1.53885642e-02, -7.22936168e-02,
         9.67836007e-02, -8.08119923e-02, -4.53453930e-03,
        -6.42011613e-02, -4.99278456e-02,  4.64197695e-02,
         2.21341159e-02,  3.13109346e-02,  9.13568810e-02,
        -4.61119786e-02, -1.02761142e-01,  3.04415803e-02,
         5.09876385e-02,  6.70140907e-02,  1.04043148e-02,
         1.63533781e-02,  3.92030925e-02,  2.17154380e-02,
         5.36603555e-02,  3.62809673e-02, -4.22139876e-02,
        -2.47226991e-02,  1.90312155e-02,  3.61724012e-02,
         6.37021065e-02, -3.21580656e-03, -8.50389246e-03,
         3.94655541e-02,  9.02654976e-03,  1.93095915e-02,
         6.60718381e-02,  1.02694826e-02, -4.43853922e-02,
        -1.56523306e-02, -1.55714452e-02,  1.32904314e-02,
        -1.16108293e-02,  4.21831980e-02, -5.44776805e-02,
         1.29237190e-01, -2.25756932e-02,  5.26203960e-02,
        -1.58436727e-02,  9.33165029e-02,  6.38023298e-03,
        -9.36159119e-03, -6.08876012e-02, -3.27307954e-02,
        -3.44816856e-02,  3.29973772e-02, -4.79392111e-02,
        -9.81300920e-02,  2.91164983e-02, -2.70903371e-02,
         1.81866940e-02, -1.73860341e-02, -4.40371446e-02,
        -7.97002539e-02,  3.01647391e-02, -6.35260791e-02,
         1.25963446e-02,  8.50250050e-02, -4.58910577e-02,
         5.81017323e-02, -2.71001961e-02,  8.42776075e-02,
        -4.09972928e-02, -3.37656252e-02,  1.02088545e-02,
        -2.54193470e-02, -1.40610306e-08,  4.94446941e-02,
        -9.04356539e-02, -6.06710389e-02,  8.29529315e-02,
        -3.29032540e-02,  4.14910428e-02,  9.99591220e-03,
         6.96138153e-03,  3.99232330e-03, -3.24333273e-02,
        -3.14656943e-02, -5.33161648e-02, -3.80913466e-02,
         1.62076708e-02,  2.45778151e-02, -7.26419240e-02,
        -6.56893849e-02, -8.23131651e-02, -8.00500885e-02,
        -5.36649227e-02,  5.60894608e-02, -1.10913524e-02,
         9.62169317e-04, -1.22690335e-01, -5.13836853e-02,
         9.96701140e-03,  1.00696282e-02,  1.07073069e-01,
         1.19758509e-02,  1.00423852e-02, -6.28261715e-02,
        -7.49697387e-02, -6.34075655e-03, -2.72201374e-02,
        -1.28096193e-01, -2.62459982e-02, -1.81464348e-02,
        -9.85360369e-02, -3.02990489e-02, -4.02614884e-02,
         9.94291082e-02,  5.35999686e-02,  2.74899956e-02,
        -5.53680817e-03,  8.43571350e-02,  8.35162252e-02,
         3.74304838e-02,  7.11937472e-02,  2.98903137e-02,
         2.32728366e-02, -3.62111740e-02,  6.20540008e-02,
         2.15148367e-02,  5.19732721e-02,  1.45337638e-02,
        -4.60966453e-02,  5.02554365e-02, -7.27027729e-02,
         2.92778984e-02,  5.62662780e-02, -3.86354700e-02,
         1.53831681e-02, -6.23094700e-02, -2.77466290e-02]], dtype=float32)

In [5]:
# Perform DBSCAN clustering
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
clusters = dbscan.fit_predict(embeddings)

# Add cluster labels to the DataFrame
df['cluster'] = clusters
df.head()

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [6]:
df[df.cluster==5]

,timestamp,source,log_message,target_label,complexity,cluster
8,2025-02-12 10:42:29,ThirdPartyAPI,nova.compute.claims [req-a07ac654-8e81-416d-bf...,Resource Usage,bert,5
26,2025-03-03 17:11:11,ModernCRM,nova.compute.claims [req-d6986b54-3735-4a42-90...,Resource Usage,bert,5
40,2025-06-19 21:42:34,ThirdPartyAPI,nova.compute.claims [req-72b4858f-049e-49e1-b3...,Resource Usage,bert,5
58,2025-09-13 14:45:14,AnalyticsEngine,nova.compute.claims [req-5c8f52bd-8e3c-41f0-95...,Resource Usage,bert,5
61,2025-04-27 11:18:18,ThirdPartyAPI,nova.compute.claims [req-d38f479d-9bb9-4276-96...,Resource Usage,bert,5
...,...,...,...,...,...,...
2336,2025-12-10 11:53:33,AnalyticsEngine,nova.compute.claims [req-97fcea79-42f7-4241-9b...,Resource Usage,bert,5
2345,2025-12-22 01:38:48,BillingSystem,nova.compute.claims [req-caeb3818-dab6-4e8d-9e...,Resource Usage,bert,5
2352,2025-02-18 00:16:44,ModernCRM,nova.compute.claims [req-98474cd9-61e1-4afe-bd...,Resource Usage,bert,5
2355,2025-11-28 18:03:55,BillingSystem,nova.compute.claims [req-6f9ecdfe-481c-4535-9b...,Resource Usage,bert,5
2372,2025-08-07 05:49:03,ThirdPartyAPI,nova.compute.claims [req-01d570b0-78a7-4719-b7...,Resource Usage,bert,5

In [7]:
cluster_counts = df['cluster'].value_counts()
large_clusters = cluster_counts[cluster_counts>10].index
for cluster in large_clusters:
    print(f"Cluster {cluster}:")
    print(df[df['cluster']==cluster]['log_message'].head(5).to_string(index=False))
    print()

Cluster 0:
nova.osapi_compute.wsgi.server [req-b9718cd8-f6...
nova.osapi_compute.wsgi.server [req-4895c258-b2...
nova.osapi_compute.wsgi.server [req-ee8bc8ba-92...
nova.osapi_compute.wsgi.server [req-f0bffbc3-5a...
nova.osapi_compute.wsgi.server [req-2bf7cfee-a2...

Cluster 5:
nova.compute.claims [req-a07ac654-8e81-416d-bfb...
nova.compute.claims [req-d6986b54-3735-4a42-907...
nova.compute.claims [req-72b4858f-049e-49e1-b31...
nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a...
nova.compute.claims [req-d38f479d-9bb9-4276-968...

Cluster 11:
User User685 logged out.
 User User395 logged in.
 User User225 logged in.
User User494 logged out.
 User User900 logged in.

Cluster 13:
Backup started at 2025-05-14 07:06:55.
Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
Backup started at 2025-11-14 08:27:43.
Backup started at 2025-12-09 10:19:11.

Cluster 7:
Multiple bad login attempts detected on user 85...
Multiple login failures occurred on user 9052 a...
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
Multiple login failures were detected for user ...

Cluster 8:
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.

Cluster 21:
System updated to version 3.9.1.
System updated to version 5.5.4.
System updated to version 4.7.4.
System updated to version 3.7.7.
System updated to version 2.6.2.

Cluster 3:
         Shard 6 replication task ended in failure
Data replication task for shard 14 did not comp...
         Data replication task failed for shard 17
            Replication of data to shard 14 failed
Data replication task for shard 6 did not complete

Cluster 4:
File data_6169.csv uploaded successfully by use...
File data_3847.csv uploaded successfully by use...
File data_7366.csv uploaded successfully by use...
File data_1206.csv uploaded successfully by use...
File data_1503.csv uploaded successfully by use...

Cluster 17:
Denied access attempt on restricted account Acc...
Unauthorized login attempt on protected account...
   Account Account9437 blocked due to failed login
Account Account7999 access denied due to login ...
Invalid login attempt made on secured account A...

Cluster 32:
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.

Cluster 6:
   Critical system unit error: unit ID Component55
System component malfunction: component ID Comp...
Critical system element is down: element ID Com...
Essential system part malfunction: part ID Comp...
Failure occurred in critical system component: ...

Cluster 16:
System reboot initiated by user User243.
System reboot initiated by user User471.
System reboot initiated by user User216.
System reboot initiated by user User639.
System reboot initiated by user User819.

Cluster 20:
   User 7662 tried to bypass API security measures
User 2367 failed to provide valid API access cr...
        User 3569 made an unauthorized API request
Unauthorized user 2968 tried to access restrict...
User 2186 attempted to access API without prope...

Cluster 9:
Account with ID 5351 created by User634.
Account with ID 7813 created by User373.
Account with ID 9827 created by User965.
Account with ID 2520 created by User546.
Account with ID 2300 created by User964.

Cluster 1:
  Email service experiencing issues with sending
        Email server encountered a sending fault
      Mail service encountered a delivery glitch
Service disruption caused by email sending error
       Email system had a problem sending emails

Cluster 10:
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...

Cluster 34:
Abnormal behavior found on server 10, possible ...
   Security alert: suspicious activity on server 1
Anomalous activity identified on server 23, sec...
Server 27 experienced potential security incide...
Server 36 experienced potential security incide...

Cluster 14:
   Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
      RAID array experienced multiple disk crashes
Multiple hard drive issues in RAID configuratio...
Identification of multiple faulty disks in RAID...

Cluster 53:
 Module X experienced an invalid data format issue
        Input format mismatch occurred in module X
Module X reported an error in input format vali...
Module X failed to process input due to formatt...
Input data format in module X was invalid or co...

Cluster 52:
Service health check was not successful because...
Invalid SSL certificate resulted in a failed se...
Service health check failure was due to an inva...
An issue with the SSL certificate caused the se...
Service health check failure was caused by an e...

Cluster 18:
Boot process terminated unexpectedly due to ker...
System encountered kernel panic during initiali...
    Boot process was stopped by kernel malfunction
System encountered kernel failure during bootup...
          Boot sequence failed due to kernel panic

Cluster 25:
         System configuration is no longer valid
Configuration is corrupted throughout the system
     Cross-system configuration failure occurred
     System configuration is experiencing errors
        Configuration malfunction is system-wide

Cluster 42:
User 5127 has escalated admin privileges withou...
            User 9745 has escalated to admin level
     User 8483 escalated privileges to admin level
            User 1987 has escalated to admin level
     User 8395 escalated privileges to admin level

Cluster 59:
Potential security threat: Admin privilege esca...
    Admin privilege escalation alert for user 2893
    Admin privilege escalation alert for user 8532
Potential security threat: Admin privilege esca...
Warning: Potential admin privilege escalation f...

Cluster 26:
        Privilege elevation detected for user 5038
Elevation of admin privileges detected for user...
Elevation of admin privileges detected for user...
User 6069 has been granted elevated admin privi...
   Admin privilege elevation warning for user 7574

In [8]:
import re
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notofication",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message, re.IGNORECASE):
            return label
    return None

In [9]:
classify_with_regex("Account with ID AD898234 created by Dhaval")

'User Action'

In [10]:
df.shape

(2410, 6)

In [11]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)
df[df.regex_label.notnull()].shape

(500, 7)

In [12]:
df_non_regex = df[df['regex_label'].isnull()].copy()
df_non_regex.shape

(1910, 7)

In [13]:
df_non_regex.head()

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None

In [14]:
print(df_non_regex['target_label'].value_counts()[df_non_regex['target_label'].value_counts()<=5].index.tolist())

['Workflow Error', 'Deprecation Warning']

In [15]:
df_non_legacy = df_non_regex[df_non_regex.source!='LegacyCRM']
df_non_legacy.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [17]:
filtered_embeddings = model.encode(df_non_legacy['log_message'].tolist())
filtered_embeddings[:2]

array([[-1.02939621e-01,  3.35459299e-02, -2.20260788e-02,
         1.55102671e-03, -9.86922998e-03, -1.78956211e-01,
        -6.34409636e-02, -6.01761751e-02,  2.81109344e-02,
         5.99620566e-02, -1.72618441e-02,  1.43365189e-03,
        -1.49560034e-01,  3.15289968e-03, -5.66030852e-02,
         2.71685794e-02, -1.49890725e-02, -3.54037471e-02,
        -3.62936258e-02, -1.45410104e-02, -5.61492424e-03,
         8.75538811e-02,  4.55120690e-02,  2.50963569e-02,
         1.00187585e-02,  1.24267116e-02, -1.39923558e-01,
         7.68696368e-02,  3.14095393e-02, -4.15245304e-03,
         4.36902978e-02,  1.71250217e-02, -8.00951123e-02,
         5.74005917e-02,  1.89092029e-02,  8.55261832e-02,
         3.96398790e-02, -1.34371832e-01, -1.44369598e-03,
         3.06706410e-03,  1.76854059e-01,  4.44887346e-03,
        -1.69275049e-02,  2.24266183e-02, -4.35049459e-02,
         6.09031459e-03, -9.98169929e-03, -6.23973384e-02,
         1.07372347e-02, -6.04892615e-03, -7.14660883e-02,
        -8.45806208e-03, -3.18020098e-02, -1.00518361e-01,
         2.25821073e-04, -1.89341456e-02, -3.17793638e-02,
         4.00861204e-02,  2.19178293e-02, -2.59528998e-02,
         5.84525205e-02, -8.12510103e-02,  2.12029032e-02,
        -5.02687618e-02,  1.32057443e-02,  1.32675562e-03,
         2.27062963e-02, -3.45793739e-02,  3.91546711e-02,
        -2.09433362e-02,  3.24824220e-03,  4.43960801e-02,
        -9.85357612e-02, -2.88894940e-02, -6.85023051e-03,
         5.38818985e-02,  6.46110624e-02, -2.45060883e-02,
         9.21828672e-02, -7.49868676e-02,  1.23995133e-02,
        -1.00026526e-01, -4.64910865e-02,  6.01569973e-02,
        -2.46480685e-02, -7.08075762e-02, -2.77270991e-02,
         9.72610861e-02,  3.85841280e-02, -1.44292591e-02,
        -7.46897538e-04, -1.04305148e-02, -1.61843114e-02,
         4.43627834e-02,  9.25997272e-03,  7.14165568e-02,
         6.37917444e-02,  4.94931042e-02, -6.02567531e-02,
         4.04805318e-02, -3.42860520e-02, -1.93880983e-02,
         6.61233813e-02,  6.01589233e-02,  1.09371580e-02,
        -5.38629526e-03,  1.44580211e-02,  9.25429612e-02,
        -3.14564072e-02, -1.84351616e-02,  9.91876144e-03,
        -1.85574312e-02,  1.31279859e-03,  2.26629745e-05,
         2.02737795e-03,  2.75257118e-02, -4.81927581e-02,
         5.42825721e-02, -7.32067078e-02,  4.88667525e-02,
         4.98489887e-02, -9.01146699e-03, -4.68905792e-02,
        -4.25886661e-02, -8.19523782e-02,  3.87106203e-02,
         7.85503760e-02,  1.46077067e-32,  1.66706145e-02,
         5.25494181e-02, -1.82448998e-02, -1.26686292e-02,
         6.52837604e-02, -2.11777370e-02, -4.06322777e-02,
         4.14947569e-02, -2.48361360e-02, -1.33068077e-02,
        -5.46754003e-02, -5.99124760e-04, -4.89244144e-03,
        -6.27359375e-02, -3.84878255e-02, -6.13543577e-02,
         8.27405676e-02,  2.34379657e-02, -8.63093045e-03,
         1.31002655e-02,  6.44215122e-02, -4.41361219e-02,
        -6.98633268e-02, -7.36060068e-02, -4.33264412e-02,
         6.96520926e-03, -5.05956709e-02, -1.60912108e-02,
        -5.66793717e-02,  3.35453334e-03,  5.34115024e-02,
         2.47761402e-02, -1.47985825e-02, -2.93242820e-02,
         7.30227828e-02, -1.86833814e-02,  8.13137069e-02,
        -2.69967411e-02, -5.68056516e-02, -6.59388527e-02,
        -5.95393451e-03,  2.85312887e-02, -7.85357729e-02,
        -2.76692025e-03, -3.26469308e-03, -9.28333178e-02,
        -7.27363080e-02, -3.31903547e-02,  1.01411119e-01,
         9.79882032e-02, -9.78740677e-02,  1.98667776e-02,
         2.38836855e-02, -1.81672368e-02, -3.73708606e-02,
         1.96551462e-03,  6.34425357e-02,  1.18271383e-02,
        -1.12041235e-02, -3.87317166e-02,  9.32424441e-02,
         4.26630303e-03, -1.66872274e-02, -6.87463731e-02,
         1.55120119e-02, -4.97755408e-02,  3.34493071e-02,
         8.00032616e-02,  2.12281998e-02,  1.34581864e-01,
        -2.30729971e-02,  5.53858951e-02,  3.07558309e-02,
        -2.93905679e-02,  2.31905282e-02, -9.34307650e-02,
         7.58034438e-02, -5.21205645e-03, -5.14523163e-02,
         3.32688987e-02,  3.67962681e-02, -1.06449733e-02,
         1.01634972e-02, -2.07650959e-02, -5.85519075e-02,
         4.79328409e-02,  2.13694554e-02,  8.76213461e-02,
         3.35497991e-03, -3.80336717e-02, -1.81205049e-02,
         6.87446119e-03,  5.15879802e-02, -4.75599207e-02,
        -6.12065569e-02, -1.45483574e-32,  4.12800582e-03,
         4.59642522e-03, -5.63900620e-02,  4.32464341e-03,
        -1.09438878e-03,  9.31957830e-03, -2.20269226e-02,
         5.79564013e-02, -1.44788129e-02,  4.64155897e-02,
         1.43542856e-01, -6.89756572e-02,  6.09631799e-02,
        -8.93743932e-02,  2.40919553e-02,  2.06010137e-02,
        -2.82415655e-02, -6.48315474e-02,  5.64795882e-02,
        -7.48343859e-03, -3.52058075e-02,  8.51060748e-02,
         1.30360126e-02,  2.02258099e-02, -1.44390957e-02,
        -4.63719293e-02,  1.77209694e-02,  1.59105789e-02,
        -9.51009542e-02, -3.54526713e-02,  2.08696295e-02,
         3.84391076e-03, -8.77918229e-02,  6.44575506e-02,
         1.44171268e-02,  3.84730729e-03,  4.70991693e-02,
         4.94661443e-02,  1.53862210e-02, -2.59578843e-02,
         9.10894498e-02,  1.83307454e-02, -5.89206740e-02,
         2.51992662e-02, -3.30373719e-02,  8.23344663e-02,
         1.74792334e-02,  6.48047328e-02, -1.19673805e-02,
        -3.31778601e-02,  3.00178099e-02,  3.54220234e-02,
        -1.39624393e-02,  6.69272617e-02,  3.87919657e-02,
         6.06916696e-02,  1.17959117e-03, -2.38786712e-02,
        -1.26930416e-01,  1.13846557e-02,  1.59290414e-02,
        -1.29426895e-02, -8.63248035e-02,  8.53658840e-03,
         6.03761002e-02,  1.51122017e-02, -1.19132400e-01,
         1.15235038e-02,  5.97089455e-02, -3.93346138e-02,
         1.55673055e-02,  1.04602147e-02, -4.72456738e-02,
        -2.59243008e-02,  9.98525135e-03,  3.07146199e-02,
        -7.14844316e-02,  6.98957872e-03, -1.55132934e-02,
         2.18863748e-02, -2.78145801e-02,  6.92733228e-02,
        -2.75903214e-02,  2.62429882e-02,  3.52561958e-02,
        -4.26419526e-02,  7.46287871e-04,  6.59866631e-02,
        -5.15106022e-02, -3.58434059e-02, -6.53442694e-03,
        -2.75858324e-02, -1.00125544e-01,  7.83325657e-02,
        -1.45799080e-02, -6.18457179e-08,  2.00325456e-02,
         6.59784898e-02, -2.04702690e-02,  1.64044425e-02,
         7.63000920e-02,  7.32182786e-02,  5.65787405e-03,
        -6.97764801e-04, -3.63795622e-03,  6.02394044e-02,
        -3.27187665e-02, -6.45838603e-02, -5.97952567e-02,
        -1.76695641e-02,  6.10138522e-03, -5.63487643e-03,
        -1.22972183e-01,  6.35819063e-02, -2.19431687e-02,
        -1.16406433e-01,  2.34366097e-02, -7.23525062e-02,
         2.31773779e-02, -6.55987337e-02, -7.42682219e-02,
         2.60146204e-02,  3.59758437e-02,  7.68432915e-02,
        -3.08057349e-02, -2.34794486e-02, -6.30426407e-02,
        -3.62158231e-02, -1.03559922e-02, -4.75602224e-02,
        -2.87522003e-02,  2.96400934e-02, -5.26889460e-03,
         5.67889474e-02, -3.74488183e-03,  3.09612919e-02,
         3.48227099e-02,  3.78607623e-02,  2.10155863e-02,
         2.70691421e-02,  5.25519922e-02,  7.16229305e-02,
        -5.53753413e-03,  4.01093587e-02,  5.16276620e-02,
        -2.67314054e-02,  5.94224073e-02, -4.29224111e-02,
        -1.19760884e-02,  3.05985343e-02, -7.40331262e-02,
         1.84221733e-02, -8.64863861e-03, -8.83557796e-02,
        -5.91984205e-02, -1.00870449e-04,  1.12913653e-01,
         4.57792962e-03, -4.25971560e-02,  3.22619220e-03],
       [ 8.04576185e-03, -3.57392468e-02,  4.93873730e-02,
        -7.19185825e-03,  6.17665821e-04, -9.05685350e-02,
         5.75594753e-02, -4.39446531e-02,  1.74751654e-02,
         5.21203354e-02, -4.62332144e-02,  2.49039568e-02,
         4.80811410e-02,  6.86636791e-02,  3.56146693e-02,
         3.00089307e-02,  2.61449553e-02, -9.05240998e-02,
        -8.02173838e-02,  5.04851192e-02, -7.90870637e-02,
        -1.76856108e-03, -2.48927083e-02,  9.02152732e-02,
         5.83697017e-03, -6.91071078e-02, -6.67965636e-02,
        -6.99113356e-03, -1.04566008e-01, -2.66473927e-02,
         3.05639915e-02,  2.02934500e-02,  2.25454606e-02,
        -4.22688248e-03,  1.11173093e-02,  6.78261071e-02,
         1.06073208e-02,  7.56636187e-02, -8.22777674e-02,
         8.45731236e-03, -6.97611943e-02, -4.21974584e-02,
        -1.05674630e-02,  2.23673414e-02,  5.64496480e-02,
         8.16504005e-03,  1.09344110e-01,  3.16564851e-02,
        -1.76923778e-02, -3.21071260e-02, -3.39975730e-02,
        -4.91787039e-04,  3.72877298e-03,  2.83771306e-02,
        -1.28521621e-02, -1.07931939e-03, -6.32418990e-02,
         6.89900517e-02,  1.77270509e-02, -5.20959869e-02,
         8.28310382e-03,  5.45032956e-02, -5.42099960e-02,
        -4.53332998e-02, -4.07494418e-02, -2.82698032e-02,
         1.23605859e-02, -2.13815887e-02, -2.36265659e-02,
         1.25318030e-02, -2.37170551e-02,  3.97411250e-02,
        -1.24362260e-01,  7.60625079e-02,  5.50833903e-02,
         8.28216821e-02,  2.97118723e-02, -1.84067544e-02,
        -1.96195133e-02,  5.54319136e-02, -3.49144675e-02,
        -4.14678045e-02, -3.37047428e-02,  7.31324255e-02,
         4.41836789e-02,  2.55247131e-02, -8.26404616e-03,
        -1.07322931e-02, -4.26243618e-02, -2.84961821e-03,
         7.38559291e-02,  2.27768160e-02,  7.15402188e-04,
         4.36012372e-02,  5.09079583e-02,  6.38482794e-02,
        -2.73155253e-02, -6.55021071e-02, -7.69265145e-02,
         3.55171151e-02,  9.60493982e-02,  2.18195897e-02,
         1.20155131e-02, -1.17863305e-02, -4.57925070e-03,
        -8.58033728e-03,  3.37150693e-02,  2.31918097e-02,
        -7.58325830e-02, -5.23879230e-02,  4.53934334e-02,
        -3.80785801e-02, -3.34904902e-02,  9.20353085e-02,
         2.87688933e-02, -3.33817117e-02, -1.95852108e-03,
        -3.04566202e-04, -1.70499310e-02,  2.85335928e-02,
        -8.81096274e-02, -4.02253084e-02, -4.00093086e-02,
        -1.03193047e-02, -2.51968410e-02,  2.14093532e-02,
         1.31045192e-01, -5.29633949e-34, -1.09651729e-01,
         1.29811550e-02,  5.92655642e-03,  4.73506264e-02,
        -8.60297494e-03, -3.67089324e-02,  3.05214860e-02,
         5.53066954e-02, -4.71985564e-02, -1.25118736e-02,
        -1.15366414e-01,  9.08002816e-03,  1.07346483e-01,
        -4.94734757e-02, -1.34290308e-02, -4.61562648e-02,
         2.45320350e-02,  9.45075881e-03,  2.04323679e-02,
        -3.99918556e-02, -4.67825681e-02,  2.21171770e-02,
        -4.58187349e-02, -8.13274179e-03, -7.65674561e-03,
         1.92284323e-02,  4.85845245e-02, -2.55903024e-02,
         1.61537575e-03, -1.37180295e-02,  9.67307854e-03,
         7.36415293e-03,  1.14088180e-02,  1.28853440e-01,
         7.71837868e-03,  7.06362426e-02,  2.54451931e-02,
         4.06523906e-02,  2.44039688e-02,  1.43776927e-02,
        -6.00932464e-02,  7.38180652e-02, -2.44700834e-02,
         8.98901224e-02,  3.17052123e-03,  1.01834461e-01,
         4.17742170e-02, -5.95177747e-02, -3.23181786e-02,
         3.80938612e-02,  1.21155744e-02, -4.07834351e-02,
         2.84823384e-02,  4.90988344e-02, -9.35708452e-03,
         6.50074184e-02,  7.23532215e-02, -1.67793650e-02,
        -8.22419859e-03, -1.61572956e-02,  5.96225746e-02,
        -3.36083621e-02,  2.12108660e-02, -6.06091060e-02,
         1.54377684e-01, -7.24145994e-02, -3.77272107e-02,
        -3.26890126e-02, -1.80384947e-03, -1.01960273e-02,
        -1.60679489e-03, -6.91846684e-02,  8.28444734e-02,
         9.88839641e-02,  3.45466682e-03, -9.90248248e-02,
        -3.52827050e-02, -7.13178664e-02, -4.96000536e-02,
        -3.43954377e-02, -8.13042298e-02,  4.81447838e-02,
         5.00682229e-03, -2.21499652e-02, -5.60057051e-02,
         1.00067258e-02, -3.59794311e-02,  1.06184311e-01,
        -4.54196706e-02,  7.16393366e-02, -2.36773379e-02,
         9.98142175e-03,  2.73602083e-02,  1.05985455e-01,
         4.60163578e-02,  9.59028719e-34, -1.12306975e-01,
         2.78912187e-02, -3.35900560e-02,  5.39242551e-02,
        -2.22291835e-02,  1.53769404e-02,  3.10411453e-02,
         3.39011215e-02,  7.43167028e-02,  3.42470743e-02,
        -3.35053541e-03, -2.05350555e-02, -3.62370089e-02,
         2.29334161e-02, -3.01992092e-02, -1.00819916e-01,
         3.29194255e-02,  6.77542984e-02,  1.35645261e-02,
        -5.20545896e-03, -6.58158362e-02,  9.54550877e-02,
        -1.34039111e-02,  1.53885642e-02, -7.22936168e-02,
         9.67836007e-02, -8.08119923e-02, -4.53453930e-03,
        -6.42011613e-02, -4.99278456e-02,  4.64197695e-02,
         2.21341159e-02,  3.13109346e-02,  9.13568810e-02,
        -4.61119786e-02, -1.02761142e-01,  3.04415803e-02,
         5.09876385e-02,  6.70140907e-02,  1.04043148e-02,
         1.63533781e-02,  3.92030925e-02,  2.17154380e-02,
         5.36603555e-02,  3.62809673e-02, -4.22139876e-02,
        -2.47226991e-02,  1.90312155e-02,  3.61724012e-02,
         6.37021065e-02, -3.21580656e-03, -8.50389246e-03,
         3.94655541e-02,  9.02654976e-03,  1.93095915e-02,
         6.60718381e-02,  1.02694826e-02, -4.43853922e-02,
        -1.56523306e-02, -1.55714452e-02,  1.32904314e-02,
        -1.16108293e-02,  4.21831980e-02, -5.44776805e-02,
         1.29237190e-01, -2.25756932e-02,  5.26203960e-02,
        -1.58436727e-02,  9.33165029e-02,  6.38023298e-03,
        -9.36159119e-03, -6.08876012e-02, -3.27307954e-02,
        -3.44816856e-02,  3.29973772e-02, -4.79392111e-02,
        -9.81300920e-02,  2.91164983e-02, -2.70903371e-02,
         1.81866940e-02, -1.73860341e-02, -4.40371446e-02,
        -7.97002539e-02,  3.01647391e-02, -6.35260791e-02,
         1.25963446e-02,  8.50250050e-02, -4.58910577e-02,
         5.81017323e-02, -2.71001961e-02,  8.42776075e-02,
        -4.09972928e-02, -3.37656252e-02,  1.02088545e-02,
        -2.54193470e-02, -1.40610306e-08,  4.94446941e-02,
        -9.04356539e-02, -6.06710389e-02,  8.29529315e-02,
        -3.29032540e-02,  4.14910428e-02,  9.99591220e-03,
         6.96138153e-03,  3.99232330e-03, -3.24333273e-02,
        -3.14656943e-02, -5.33161648e-02, -3.80913466e-02,
         1.62076708e-02,  2.45778151e-02, -7.26419240e-02,
        -6.56893849e-02, -8.23131651e-02, -8.00500885e-02,
        -5.36649227e-02,  5.60894608e-02, -1.10913524e-02,
         9.62169317e-04, -1.22690335e-01, -5.13836853e-02,
         9.96701140e-03,  1.00696282e-02,  1.07073069e-01,
         1.19758509e-02,  1.00423852e-02, -6.28261715e-02,
        -7.49697387e-02, -6.34075655e-03, -2.72201374e-02,
        -1.28096193e-01, -2.62459982e-02, -1.81464348e-02,
        -9.85360369e-02, -3.02990489e-02, -4.02614884e-02,
         9.94291082e-02,  5.35999686e-02,  2.74899956e-02,
        -5.53680817e-03,  8.43571350e-02,  8.35162252e-02,
         3.74304838e-02,  7.11937472e-02,  2.98903137e-02,
         2.32728366e-02, -3.62111740e-02,  6.20540008e-02,
         2.15148367e-02,  5.19732721e-02,  1.45337638e-02,
        -4.60966453e-02,  5.02554365e-02, -7.27027729e-02,
         2.92778984e-02,  5.62662780e-02, -3.86354700e-02,
         1.53831681e-02, -6.23094700e-02, -2.77466290e-02]], dtype=float32)

In [18]:
x = filtered_embeddings
y = df_non_legacy['target_label']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [ ]:
import joblib

joblib.dump(clf, '../models/log_classifier.joblib')

['models/log_classifier.joblib']